### ISSUE TITLE
network connectivity inside boot2docker machine

### ISSUE THREAD

**Issue by corporate-gadfly** [fnichol/dvm#4] opened 2014-01-09 01:59 UTC
Thank you for your work. Seems really useful.

I am a newbie with docker, boot2docker and Tiny Core. Seem to be having a problem with dvm and network connectivity. On OSX 10.9.1 and VirtualBox 3.4.6.

```
$ docker version
Client version: 0.7.4
Go version (client): go1.2
Git commit (client): 010d74e
Server version: 0.7.1
Git commit (server): 88df052
Go version (server): go1.2
Last stable version: 0.7.4, please update docker
```

I followed the instructions by installing docker from brew and then installing dvm. `DOCKER_HOST` is set to `tcp://192.168.42.43:4243`. If I `dvm ssh` into the VM, I don't seem to have any network connectivity. E.g.,

```
$ dvm ssh
                        ##        .
                  ## ## ##       ==
               ## ## ## ##      ===
           /""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
           \______ o          __/
             \    \        __/
              \____\______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
docker@boot2docker:~$ nslookup github.com
Server:    127.0.0.1
Address 1: 127.0.0.1 boot2docker

nslookup: can't resolve 'github.com'
```

As a result, `docker run` commands never get off the ground. E.g.,

```
$ docker run ubuntu cat /etc/lsb-release
Unable to find image 'ubuntu' (tag: latest) locally
Pulling repository ubuntu
2014/01/08 20:52:22 Get https://index.docker.io/v1/repositories/ubuntu/images: dial tcp: lookup index.docker.io: no DNS servers
```

Output of `dvm up`:

```
$ dvm up
Bringing machine 'dvm' up with 'virtualbox' provider...
[dvm] Importing base box 'boot2docker-0.3.0-1'...
[dvm] Matching MAC address for NAT networking...
[dvm] Setting the name of the VM...
[dvm] Clearing any previously set forwarded ports...
[dvm] Fixed port collision for 22 => 2222. Now on port 2200.
[dvm] Clearing any previously set network interfaces...
[dvm] Preparing network interfaces based on configuration...
[dvm] Forwarding ports...
[dvm] -- 22 => 2200 (adapter 1)
[dvm] Running 'pre-boot' VM customizations...
[dvm] Booting VM...
[dvm] Waiting for machine to boot. This may take a few minutes...
[dvm] Machine booted and ready!
No installation found.
The guest's platform is currently not supported, will try generic Linux method...
Copy iso file /Applications/VirtualBox.app/Contents/MacOS/VBoxGuestAdditions.iso into the box /tmp/VBoxGuestAdditions.iso
Installing Virtualbox Guest Additions 4.3.6 - guest version is 
Verifying archive integrity... All good.
Uncompressing VirtualBox 4.3.6 Guest Additions for Linux............
VirtualBox Guest Additions installer
Copying additional installer modules ...
add_symlink: link directory /usr/src does not exist
Installing additional modules ...
As our installer does not recognize your Linux distribution, we were unable to
set up the initialization script vboxadd correctly.  The script has been copied
copied to the /etc/init.d directory.  You should set up your system to start
it at system start, or start it manually before using VirtualBox.

If you would like to help us add support for your distribution, please open a
new ticket on http://www.virtualbox.org/wiki/Bugtracker.
/sbin/modprobe: invalid option -- 'c'
BusyBox v1.20.2 (2012-08-07 01:31:01 UTC) multi-call binary.

Usage: modprobe [-alrqvsDb] MODULE [symbol=value]...

    -a  Load multiple MODULEs
    -l  List (MODULE is a pattern)
    -r  Remove MODULE (stacks) or do autoclean
    -q  Quiet
    -v  Verbose
    -s  Log to syslog
    -D  Show dependencies
    -b  Apply blacklist to module names too

Removing existing VirtualBox non-DKMS kernel modules ...done.
Building the VirtualBox Guest Additions kernel modules
The make utility was not found. If the following module compilation fails then
this could be the reason and you should try installing it.

The gcc utility was not found. If the following module compilation fails then
this could be the reason and you should try installing it.

The headers for the current running kernel were not found. If the following
module compilation fails then this could be the reason.

Building the main Guest Additions module ...fail!
(Look at /var/log/vboxadd-install.log to find out what went wrong)
Doing non-kernel setup of the Guest Additions ...done.
As our installer does not recognize your Linux distribution, we were unable to
set up the initialization script vboxadd-service correctly.  The script has been copied
copied to the /etc/init.d directory.  You should set up your system to start
it at system start, or start it manually before using VirtualBox.

If you would like to help us add support for your distribution, please open a
new ticket on http://www.virtualbox.org/wiki/Bugtracker.
As our installer does not recognize your Linux distribution, we were unable to
set up the initialization script vboxadd-x11 correctly.  The script has been copied
copied to the /etc/init.d directory.  You should set up your system to start
it at system start, or start it manually before using VirtualBox.

If you would like to help us add support for your distribution, please open a
new ticket on http://www.virtualbox.org/wiki/Bugtracker.
Installing the Window System drivers ...fail!
(Could not find the X.Org or XFree86 Window System.)
An error occurred during installation of VirtualBox Guest Additions 4.3.6. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
rm: remove '/tmp/VBoxGuestAdditions.iso'? 
[dvm] No guest additions were detected on the base box for this VM! Guest
additions are required for forwarded ports, shared folders, host only
networking, and more. If SSH fails on this machine, please install
the guest additions and repackage the box to continue.

This is not an error message; everything may continue to work properly,
in which case you may ignore this message.
[dvm] Configuring and enabling network interfaces...
[dvm] Running provisioner: shell...
[dvm] Running: inline script
---> Configuring docker to bind to tcp/4243 and restarting
```

Any help is appreciated. Sorry for writing a whole book.

**Comment by corporate-gadfly** [comment] 2014-01-09 16:25
This can be closed. I had `vboxnet0` host-only networking inside Virtual Box. Once I removed that, I have no problems with network connectivity.

Sorry for the noise.

**Comment by fnichol** [comment] 2014-01-09 16:25
Oh excellent news!

**Comment by cjbottaro** [comment] 2014-01-10 00:29
I have the exact same problem and I don't understand the solution.  I setup dvm using exactly the commands listed in the readme.

I feel like "dvm up" should give a completely functional vm without any further manual tweaking, but in the mean time, what is the workaround?

**Comment by cjbottaro** [comment] 2014-01-10 00:40
I added `nameserver 8.8.8.8` to `/etc/resolv.conf` in the vm and things are working now.

**Comment by garyfleming** [comment] 2014-01-10 09:27
Adding `nameserver 8.8.8.8` to `/etc/resolv.conf` doesn't seem to work for me. I'm seeing the same issue.

**Comment by wietsevenema** [comment] 2014-01-10 11:07
Using VirtualBox 4.6.3. Adding `nameserver 8.8.8.8` is not a solution for me either.

**Comment by wietsevenema** [comment] 2014-01-10 15:09
Applied https://github.com/fnichol/dvm/commit/35ae30c557242d74117a56200b2b8b424c58b3ed which fixed this for me

**Comment by jopecko** [comment] 2014-01-11 23:40
:+1: applying the patch mentioned by @wietsevenema fixed this issue for me as well. Thanks!

**Comment by fnichol** [comment] 2014-01-14 20:30
I'd rather have a complete solution here, but I suspect the DNS resolving issue is a problem with VirtualBox's networking under the hood. I've been trying to find a more thorough solution here, but in the meantime I'll merge in 35ae30c557242d74117a56200b2b8b424c58b3ed. Thanks everyone for your continued feedback!

**Comment by wietsevenema** [comment] 2014-01-15 09:20
Maybe set the nameserver to 10.0.2.3 ? https://forums.virtualbox.org/viewtopic.php?f=1&t=9410&start=0

**Comment by corporate-gadfly** [comment] 2014-01-15 16:05
The underlying issue might still be there.

This morning the VM was unable to connect again. The difference this time was that I had taken my laptop home in the evening and possibly used it on my home Wifi connection. Then I brought it back to work and used the usual wired connection and it was hosed. Sadly, I didn't do any forensics at this point and a `dvm halt` followed by `dvm up` fixed it for me.

**Comment by Peeja** [comment] 2014-01-16 15:01
@corporate-gadfly Do you have 35ae30c in your build? I installed it with:

```
$ brew reinstall --head dvm
$ dvm reload
```

**Comment by fnichol** [comment] 2014-01-16 21:10
I'm in the process of getting a release out the door with boot2docker 0.4.0 and the above commits in master. Then we should have a new baseline to troubleshoot any issues here.

**Comment by fnichol** [comment] 2014-01-16 22:26
Release 0.3.0 is out now https://github.com/fnichol/dvm/releases/tag/v0.3.0. Let's see if there are still issues now

**Comment by Peeja** [comment] 2014-01-17 13:52
@corporate-gadfly Can you reproduce this and see if you can ping 8.8.8.8? From what's in your original report, it's not clear if you're hitting a connectivity issue or a DNS issue.

**Comment by fnichol** [comment] 2014-04-11 15:28
I'm going to hope that this issue is effectively resolved as newer versions of VirtualBox, Vagrant, boot2docker-vagrant-box, and boot2docker have been since been released. If I'm incorrect, please open a new pull request & we'll re-evaluate the state of things. Thanks!

**Closed as completed by fnichol** 2014-04-11 15:28 UTC
